name: mahami
description: Todo app
version: 1.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  uuid: ^4.5.1
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1  

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/1.png
    - assets/2.png
    - assets/3.png
